from selenium import webdriver
from time import sleep

driver = webdriver.Chrome()
driver.get('http://www.baidu.com')
driver.maximize_window()
sleep(1)
driver.minimize_window()
sleep(1)
driver.set_window_size(1024,768)
sleep(1)
driver.refresh()
sleep(1)
print(driver.title)
driver.get('http://www.qq.com')
print(driver.title)
driver.refresh()
driver.back()
driver.forward()
sleep(3)
driver.quit()
